#ifndef CP437_H
#define CP437_H

/* Windows CP437 codepage */

#define CP_NULL 0 // '\0'
#define CP_SMILE 1 // '☺'
#define CP_INV_SMILE 2 // '☻'
#define CP_HEART 3 // '♥'
#define CP_DIAMOND 4 // '♦'
#define CP_CLUB 5 // '♣'
#define CP_SPADE 6 // '♠'
#define CP_BULLET 7 // '•'
#define CP_INV_BULLET 8 // '◘'
#define CP_CIRCLE 9 // '○'
#define CP_INV_CIRCLE 10 // '◙'
#define CP_MALE 11 // '♂'
#define CP_FEMALE 12 // '♀'
#define CP_EIGHTH 13 // '♪'
#define CP_EIGHTH_PAIR 14 // '♫'
#define CP_SOL 15 // '☼'
#define CP_RIGHT_TRIANGLE 16 // '►'
#define CP_LEFT_TRIANGLE 17 // '◄'
#define CP_VERTICAL_ARROWS 18 // '↕'
#define CP_DOUBLE_EXCLAMATION 19 // '‼'
#define CP_PILCROW 20 // '¶'
#define CP_SILCROW 21 // '§'
#define CP_RECTANGLE 22 // '▬'
#define CP_VERTICAL_BASE_ARROWS 23 // '↨'
#define CP_UP_ARROW 24 // '↑'
#define CP_DOWN_ARROW 25 // '↓'
#define CP_RIGHT_ARROW 26 // '→'
#define CP_LEFT_ARROW 27 // '←'
#define CP_RIGHT_ANGLE 28 // '∟'
#define CP_HORIZONTAL 29 // '↔'
#define CP_UP_TRIANGLE 30 // '▲'
#define CP_DOWN_TRIANGLE 31 // '▼'
#define CP_SPACE 32 // ' '
#define CP_EXCLAMATION 33 // '!'
#define CP_DOUBLE_QUOTE 34 // '\''
#define CP_HASH 35 // '#'
#define CP_DOLLAR 36 // '$''
#define CP_PERCENT 37 // '%'
#define CP_AMPERSAND 38 // '&'
#define CP_APOSTROPHE 39 // '''
#define CP_OPEN_PAREN 40 // '('
#define CP_CLOSED_PAREN 41 // ')'
#define CP_ASTERISK 42 // '*'
#define CP_PLUS 43 // '+'
#define CP_COMMA 44 // ','
#define CP_MINUS 45 // '-'
#define CP_PERIOD 46 // '.'
#define CP_FORWARD_SLASH 47 // '/'
#define CP_0 48 // '0'
#define CP_1 49 // '1'
#define CP_2 50 // '2'
#define CP_3 51 // '3'
#define CP_4 52 // '4'
#define CP_5 53 // '5'
#define CP_6 54 // '6'
#define CP_7 55 // '7'
#define CP_8 56 // '8'
#define CP_9 57 // '9'
#define CP_COLON 58 // ':'
#define CP_SEMICOLON 59 // ';'
#define CP_LESS 60 // '<'
#define CP_EQUALS 61 // '='
#define CP_GREATER 62 // '>'
#define CP_QUESTION 63 // '?'
#define CP_AT 64 // '@'
#define CP_CAP_A 65 // 'A'
#define CP_CAP_B 66 // 'B'
#define CP_CAP_C 67 // 'C'
#define CP_CAP_D 68 // 'D'
#define CP_CAP_E 69 // 'E'
#define CP_CAP_F 70 // 'F'
#define CP_CAP_G 71 // 'G'
#define CP_CAP_H 72 // 'H'
#define CP_CAP_I 73 // 'I'
#define CP_CAP_J 74 // 'J'
#define CP_CAP_K 75 // 'K'
#define CP_CAP_L 76 // 'L'
#define CP_CAP_M 77 // 'M'
#define CP_CAP_N 78 // 'N'
#define CP_CAP_O 79 // 'O'
#define CP_CAP_P 80 // 'P'
#define CP_CAP_Q 81 // 'Q'
#define CP_CAP_R 82 // 'R'
#define CP_CAP_S 83 // 'S'
#define CP_CAP_T 84 // 'T'
#define CP_CAP_U 85 // 'U'
#define CP_CAP_V 86 // 'V'
#define CP_CAP_W 87 // 'W'
#define CP_CAP_X 88 // 'X'
#define CP_CAP_Y 89 // 'Y'
#define CP_CAP_Z 90 // 'Z'
#define CP_OPEN_SQUARE_BRACKET 91 // '['
#define CP_BACKSLASH 92 // '\\'
#define CP_CLOSED_SQUARE_BRACKET 93 // ']'
#define CP_CARET 94 // '^'
#define CP_LOW_LINE 95 // '_'
#define CP_GRAVE 96 // '`'
#define CP_LOW_A 97 // 'a'
#define CP_LOW_B 98 // 'b'
#define CP_LOW_C 99 // 'c'
#define CP_LOW_D 100 // 'd'
#define CP_LOW_E 101 // 'e'
#define CP_LOW_F 102 // 'f'
#define CP_LOW_G 103 // 'g'
#define CP_LOW_H 104 // 'h'
#define CP_LOW_I 105 // 'i'
#define CP_LOW_J 106 // 'j'
#define CP_LOW_K 107 // 'k'
#define CP_LOW_L 108 // 'l'
#define CP_LOW_M 109 // 'm'
#define CP_LOW_N 110 // 'n'
#define CP_LOW_O 111 // 'o'
#define CP_LOW_P 112 // 'p'
#define CP_LOW_Q 113 // 'q'
#define CP_LOW_R 114 // 'r'
#define CP_LOW_S 115 // 's'
#define CP_LOW_T 116 // 't'
#define CP_LOW_U 117 // 'u'
#define CP_LOW_V 118 // 'v'
#define CP_LOW_W 119 // 'w'
#define CP_LOW_X 120 // 'x'
#define CP_LOW_Y 121 // 'y'
#define CP_LOW_Z 122 // 'z'
#define CP_OPEN_CURLY_BRACE 123 // '{'
#define CP_BROKEN_BAR 124 // '|'
#define CP_CLOSED_CURLY_BRACE 125 // '}'
#define CP_TILDE 126 // '~'
#define CP_HOUSE 127 // '⌂'
#define CP_CAP_C_CEDILLA 128 // 'Ç'
#define CP_LOW_U_DIAERESIS 129 // 'ü'
#define CP_LOW_E_ACUTE 130 // 'é'
#define CP_LOW_A_CIRCUMFLEX 131 // 'â'
#define CP_LOW_A_DIARESIS 132 // 'ä'
#define CP_LOW_A_GRAVE 133 // 'à'
#define CP_LOW_A_RING 134 // 'å'
#define CP_LOW_C_CEDILLA 135 // 'ç'
#define CP_LOW_E_CIRCUMFLEX 136 // 'ê'
#define CP_LOW_E_DIARESIS 137 // 'ë'
#define CP_LOW_E_GRAVE 138 // 'è'
#define CP_LOW_I_DIARESIS 139 // 'ï'
#define CP_LOW_I_CIRCUMFLEX 140 // 'î'
#define CP_LOW_I_GRAVE 141 // 'ì'
#define CP_CAP_A_DIARESIS 142 // 'Ä'
#define CP_CAP_A_RING 143 // 'Å'
#define CP_CAP_E_ACUTE 144 // 'É'
#define CP_LOW_AE 145 // 'æ'
#define CP_CAP_AE 146 // 'Æ'
#define CP_LOW_O_CIRCUMFLEX 147 // 'ô'
#define CP_LOW_O_DIARESIS 148 // 'ö'
#define CP_LOW_O_GRAVE 149 // 'ò'
#define CP_LOW_U_CIRCUMFLEX 150 // 'û'
#define CP_LOW_U_GRAVE 151 // 'ù'
#define CP_LOW_Y_DIARESIS 152 // 'ÿ'
#define CP_CAP_O_DIARESIS 153 // 'Ö'
#define CP_CAP_U_DIARESIS 154 // 'Ü'
#define CP_CENT 155 // '¢
#define CP_POUND 156 // '£'
#define CP_YEN 157 // '¥'
#define CP_PESETA 158 // '₧'
#define CP_F_HOOK 159 // 'ƒ'
#define CP_LOW_A_ACUTE 160 // 'á'
#define CP_LOW_I_ACUTE 161 // 'í'
#define CP_LOW_O_ACUTE 162 // 'ó'
#define CP_LOW_U_ACUTE 163 // 'ú'
#define CP_LOW_N_TILDE 164 // 'ñ'
#define CP_CAPITAL_N_TILDE 165 // 'Ñ'
#define CP_FEMALE_ORDINAL 166 // 'ª'
#define CP_MALE_ORDINAL 167 // 'º'
#define CP_INV_QUESTION 168 // '¿'
#define CP_NEGATION 169 // '⌐'
#define CP_INV_NEGATION 170 // '¬'
#define CP_HALF 171 // '½'
#define CP_QUARTER 172 // '¼'
#define CP_INV_EXCLAMATION 173 // '¡'
#define CP_LEFT_DOUBLE_ANGLE 174 // '«'
#define CP_RIGHT_DOUBLE_ANGLE 175 // '»'
#define CP_LIGHT_SHADE 176 // '░'
#define CP_MEDIUM_SHADE 177 // '▒'
#define CP_DARK_SHADE 178 // '▓'
#define CP_THIN_VERTICAL 179 // '│'
#define CP_THIN_LEFT_THIN_VERTICAL 180 // '┤'
#define CP_THICK_LEFT_THIN_VERTICAL 181 // '╡'
#define CP_THIN_LEFT_THICK_VERTICAL 182 // '╢'
#define CP_THIN_LEFT_THICK_DOWN 183 // '╖'
#define CP_THICK_LEFT_THIN_DOWN 184 // '╕'
#define CP_THICK_LEFT_THICK_VERTICAL 185 // '╣'
#define CP_THICK_VERTICAL 186 // '║'
#define CP_THICK_LEFT_THICK_DOWN 187 // '╗'
#define CP_THICK_LEFT_THICK_UP 188 // '╝'
#define CP_THIN_LEFT_THICK_UP 189 // '╜'
#define CP_THICK_LEFT_THIN_UP 190 // '╛'
#define CP_THIN_LEFT_THIN_DOWN 191 // '┐'
#define CP_THIN_RIGHT_THIN_UP 192 // '└'
#define CP_THIN_HORIZONTAL_THIN_UP 193 // '┴'
#define CP_THIN_HORIZONTAL_THIN_DOWN 194 // '┬'
#define CP_THIN_RIGHT_THIN_VERTICAL 195 // '├'
#define CP_THIN_HORIZONTAL 196 // '─'
#define CP_THIN_HORIZONTAL_THIN_VERTICAL 197 // '┼'
#define CP_THICK_RIGHT_THIN_VERTICAL 198 // '╞'
#define CP_THIN_RIGHT_THICK_VERTICAL 199 // '╟'
#define CP_THICK_RIGHT_THICK_UP 200 // '╚'
#define CP_THICK_RIGHT_THICK_DOWN 201 // '╔'
#define CP_THICK_HORIZONTAL_THICK_UP 202 // '╩'
#define CP_THICK_HORIZONTAL_THICK_DOWN 203 // '╦'
#define CP_THICK_RIGHT_THICK_VERTICAL 204 // '╠'
#define CP_THICK_HORIZONTAL 205 // '═'
#define CP_THICK_HORIZONTAL_THICK_VERTICAL 206 // '╬'
#define CP_THICK_HORIZONTAL_THIN_UP 207 // '╧'
#define CP_THIN_HORIZONTAL_THICK_UP 208 // '╨'
#define CP_THICK_HORIZONTAL_THIN_DOWN 209 // '╤'
#define CP_THIN_HORIZONTAL_THICK_DOWN 210 // '╥'
#define CP_THIN_RIGHT_THICK_UP 211 // '╙'
#define CP_THICK_RIGHT_THIN_UP 212 // '╘'
#define CP_THICK_RIGHT_THIN_DOWN 213 // '╒'
#define CP_THIN_RIGHT_THICK_DOWN 214 // '╓'
#define CP_THIN_HORIZONTAL_THICK_VERTICAL 215 // '╫'
#define CP_THICK_HORIZONTAL_THIN_VERTICAL 216 // '╪'
#define CP_THIN_LEFT_THIN_UP 217 // '┘'
#define CP_THIN_RIGHT_THIN_DOWN 218 // '┌'
#define CP_BLOCK 219 // '█'
#define CP_LOWER_BLOCK 220 // '▄'
#define CP_LEFT_BLOCK 221 // '▌'
#define CP_RIGHT_BLOCK 222 // '▐'
#define CP_TOP_BLOCK 223 // '▀'
#define CP_ALPHA 224 // 'α'
#define CP_BETA 225 // 'ß'
#define CP_GAMMA 226 // 'Γ'
#define CP_PI 227 // 'π'
#define CP_CAP_SIGMA 228 // 'Σ'
#define CP_LOW_SIGMA 229 // 'σ'
#define CP_MU 230 // 'µ'
#define CP_TAU 231 // 'τ'
#define CP_CAP_PHI 232 // 'Φ'
#define CP_THETA 233 // 'Θ'
#define CP_OMEGA 234 // 'Ω'
#define CP_DELTA 235 // 'δ'
#define CP_INFINITY 236 // '∞'
#define CP_LOW_PHI 237 // 'φ'
#define CP_LOW_EPSILON 238 // 'ε'
#define CP_INTERSECTION 239 // '∩'
#define CP_TRIPPLE_BAR 240 // '≡'
#define CP_PLUS_MINUS 241 // '±'
#define CP_GREATER_EQUAL 242 // '≥'
#define CP_LESS_EQUAL 243 // '≤'
#define CP_INTEGRAL_TOP 244 // '⌠'
#define CP_INTEGRAL_BOTTOM 245 // '⌡'
#define CP_DIVISION 246 // '÷'
#define CP_ABOUT 247 // '≈'
#define CP_DEGREE 248 // '°'
#define CP_ALT_BULLET 249 // '∙'
#define CP_INTERPUNCT 250 // '·'
#define CP_SQRT 251 // '√'
#define CP_SUB_N 252 // 'ⁿ'
#define CP_SUPER_2 253 // '²'
#define CP_SQUARE 254 // '■'
#define CP_NBSP 255 // ' '

/* Windows CP437 box drawing characters */

#define BOX_DLR 0315 /* ═ */
#define BOX_DUD 0272 /* ║ */
#define BOX_DUL 0274 /* ╝ */
#define BOX_DUR 0310 /* ╚ */
#define BOX_DDL 0273 /* ╗ */
#define BOX_DDR 0311 /* ╔ */
#define BOX_DUDL 0271 /* ╣ */
#define BOX_DUDR 0314 /* ╠ */
#define BOX_DULR 0312 /* ╩ */
#define BOX_DDLR 0313 /* ╦ */
#define BOX_DUDLR 0316 /* ╬ */
#define BOX_DU_SL 0275 /* ╜, not in CP850 */
#define BOX_DU_SR 0323 /* ╙, not in CP850 */
#define BOX_DD_SL 0267 /* ╖, not in CP850 */
#define BOX_DD_SR 0326 /* ╓, not in CP850 */
#define BOX_DL_SU 0276 /* ╛, not in CP850 */
#define BOX_DL_SD 0270 /* ╕, not in CP850 */
#define BOX_DR_SU 0324 /* ╘, not in CP850 */
#define BOX_DR_SD 0325 /* ╒, not in CP850 */
#define BOX_DU_SLR 0320 /* ╨, not in CP850 */
#define BOX_DD_SLR 0322 /* ╥, not in CP850 */
#define BOX_DL_SUD 0265 /* ╡, not in CP850 */
#define BOX_DR_SUD 0306 /* ╞, not in CP850 */
#define BOX_DLR_SU 0317 /* ╧, not in CP850 */
#define BOX_DLR_SD 0321 /* ╤, not in CP850 */
#define BOX_DLR_SUD 0330 /* ╪, not in CP850 */
#define BOX_DUD_SL 0266 /* ╢, not in CP850 */
#define BOX_DUD_SR 0307 /* ╟, not in CP850 */
#define BOX_DUD_SLR 0327 /* ╫, not in CP850 */
#define BOX_SLR 0304 /* ─ */
#define BOX_SUD 0263 /* │ */
#define BOX_SUL 0331 /* ┘ */
#define BOX_SUR 0300 /* └ */
#define BOX_SDL 0277 /* ┐ */
#define BOX_SDR 0332 /* ┌ */
#define BOX_SULR 0301 /* ┴ */
#define BOX_SDLR 0302 /* ┬ */
#define BOX_SUDL 0264 /* ┤ */
#define BOX_SUDR 0303 /* ├ */
#define BOX_SUDLR 0305 /* ┼ */

#endif // CP437_H
